#pragma once
void addElemComanda();
void deleteElemComanda();
void updateElemComanda();
void getAllComanda();
void addElemMancare();
void deleteElemMancare();
void updateElemMancare();
void getAllMancare();
void addElemShopping();
void deleteElemShopping();
void updateElemShopping();
void getAllShopping();
